sudo: required

services:
- docker

install: skip

jobs:
  include:
    - &deploy-stage
      stage: build and deploy
      script:
        # set up QEMU
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        # build
        - >
          docker build -t grafana:${DOCKER_TAG} -f Dockerfile \
            --build-arg BASE_IMAGE=${DOCKER_FROM} \
            --build-arg VERSION=${GRAFANA_VERSION} \
            --build-arg ARCH=${GRAFANA_ARCH} \
            .
      after_success:
        - |
          echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
          if [ "$TRAVIS_BRANCH" == "master" ]; then
              docker tag grafana:${DOCKER_TAG} rycus86/grafana:${DOCKER_TAG}${MODIFIER}
              docker push rycus86/grafana:${DOCKER_TAG}${MODIFIER}
          elif [ "$TRAVIS_BRANCH" == "${GRAFANA_VERSION}${MODIFIER}" ]; then
              docker tag grafana:${DOCKER_TAG} rycus86/grafana:${GRAFANA_VERSION}${MODIFIER}-${DOCKER_TAG}
              docker push rycus86/grafana:${GRAFANA_VERSION}${MODIFIER}-${DOCKER_TAG}
          fi
      env:
        - DOCKER_FROM=debian:stable-slim
        - DOCKER_TAG=amd64
        - GRAFANA_ARCH=amd64

    - <<: *deploy-stage
      env:
        - DOCKER_FROM=rycus86/armhf-debian-qemu
        - DOCKER_TAG=armhf
        - GRAFANA_ARCH=armhf

    - <<: *deploy-stage
      env:
        - DOCKER_FROM=rycus86/arm64v8-debian-qemu
        - DOCKER_TAG=aarch64
        - GRAFANA_ARCH=arm64

    - stage: manifest
      script:
        - |
          if [ "$TRAVIS_BRANCH" == "${GRAFANA_VERSION}${MODIFIER}" ]; then
              sed -i "s#rycus86/grafana:#rycus86/grafana:${GRAFANA_VERSION}${MODIFIER}-#" manifest.yml
              sed -i "s#rycus86/grafana:${GRAFANA_VERSION}${MODIFIER}-latest#rycus86/grafana:${GRAFANA_VERSION}${MODIFIER}#" manifest.yml
          fi
        - echo ${DOCKER_PASSWORD} | docker login --username "rycus86" --password-stdin
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml

env:
  global:
  - GRAFANA_VERSION=5.2.3
  - MODIFIER=
