sudo: required

services:
- docker

addons:
  apt:
    packages:
      - docker-ce

script:
# set up the base image
- sed -i "s#^FROM debian:stable-slim#FROM ${DOCKER_FROM}#" Dockerfile
# build
- >
  docker build -t grafana:$DOCKER_TAG -f Dockerfile \
    --build-arg VERSION=$GRAFANA_VERSION \
    --build-arg CC=$CC \
    --build-arg CC_PKG=$CC_PKG \
    --build-arg CC_GOARCH=$CC_GOARCH \
    .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="rycus86" -p="$DOCKER_PASSWORD" && \
      docker tag grafana:$DOCKER_TAG rycus86/grafana:$DOCKER_TAG && \
      docker push rycus86/grafana:$DOCKER_TAG
  elif [ "$TRAVIS_BRANCH" == "$GRAFANA_VERSION" ]; then
      docker login -u="rycus86" -p="$DOCKER_PASSWORD" && \
      docker tag grafana:$DOCKER_TAG rycus86/grafana:$GRAFANA_VERSION-$DOCKER_TAG && \
      docker push rycus86/grafana:$GRAFANA_VERSION-$DOCKER_TAG
  fi

env:
  global:
  - GRAFANA_VERSION=4.4.3
  matrix:
  - DOCKER_FROM=rycus86/armhf-debian-qemu    DOCKER_TAG=armhf    CC=arm-linux-gnueabihf-gcc  CC_PKG=gccgo-arm-linux-gnueabihf  CC_GOARCH=arm
  - DOCKER_FROM=rycus86/arm64v8-debian-qemu  DOCKER_TAG=aarch64  CC=aarch64-linux-gnu-gcc    CC_PKG=gccgo-aarch64-linux-gnu    CC_GOARCH=arm64
