sudo: required

services:
- docker

install: skip

jobs:
  include:
    - &deploy-stage
      stage: build and deploy
      script:
        # set up QEMU
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        # build
        - >
          docker build -t grafana:${DOCKER_TAG} -f ${DOCKERFILE} \
            --build-arg BASE_IMAGE=${DOCKER_FROM} \
            --build-arg VERSION=${GRAFANA_VERSION} \
            --build-arg ARCH=${GRAFANA_ARCH} \
            .
      after_success:
        - |
          echo ${DOCKER_PASSWORD} | docker login --username "povilasv" --password-stdin
          if [ "$TRAVIS_TAG" == "master" ]; then
              docker tag grafana:${DOCKER_TAG} povilasv/grafana:${DOCKER_TAG}${MODIFIER}
              docker push povilasv/grafana:${DOCKER_TAG}${MODIFIER}
          elif [ "$TRAVIS_TAG" == "${GRAFANA_VERSION}${MODIFIER}" ]; then
              docker tag grafana:${DOCKER_TAG} povilasv/grafana:${GRAFANA_VERSION}${MODIFIER}-${DOCKER_TAG}
              docker push povilasv/grafana:${GRAFANA_VERSION}${MODIFIER}-${DOCKER_TAG}
          fi
      env:
        - DOCKERFILE=Dockerfile
        - DOCKER_FROM=debian:stable-slim
        - DOCKER_TAG=amd64
        - GRAFANA_ARCH=amd64

    - <<: *deploy-stage
      env:
        - DOCKERFILE=Dockerfile.armhf
          # - DOCKER_FROM=povilasv/armhf-debian-qemu # unused
        - DOCKER_TAG=armhf
        - GRAFANA_ARCH=armhf

    - <<: *deploy-stage
      env:
        - DOCKERFILE=Dockerfile
        - DOCKER_FROM=povilasv/arm64v8-debian-qemu
        - DOCKER_TAG=aarch64
        - GRAFANA_ARCH=arm64

    - stage: manifest
      script:
        - |
          if [ "$TRAVIS_TAG" == "${GRAFANA_VERSION}${MODIFIER}" ]; then
              sed -i "s#povilasv/grafana:#povilasv/grafana:${GRAFANA_VERSION}${MODIFIER}-#" manifest.yml
              sed -i "s#povilasv/grafana:${GRAFANA_VERSION}${MODIFIER}-latest#povilasv/grafana:${GRAFANA_VERSION}${MODIFIER}#" manifest.yml
          fi
        - echo ${DOCKER_PASSWORD} | docker login --username "povilasv" --password-stdin
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v1.0.0-rc3/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml

env:
  global:
  - GRAFANA_VERSION=6.1.6
  - MODIFIER=
